# Generated by Django 3.0.8 on 2020-09-19 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio_pic',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 11, 50, 58, 378390)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(default=''),
        ),
    ]
