# Generated by Django 3.0.8 on 2020-09-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pledge_kudos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='raised',
            new_name='total_raised',
        ),
    ]
