# Generated by Django 3.0.8 on 2020-09-26 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200922_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 2, 29, 21, 212567, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='num_supporters',
            field=models.IntegerField(default=0),
        ),
    ]
