# Generated by Django 3.0.8 on 2020-09-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200926_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_supporters',
            field=models.IntegerField(),
        ),
    ]
