# Generated by Django 3.0.8 on 2020-10-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201020_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='num_supporters',
            field=models.IntegerField(default=0),
        ),
    ]
